version: '3'

# to restore a dump from folder
# docker-compose exec -T mongo mongorestore /dump
services:
  base:
    build:
      context: .
      target: build
    scale: 0

  mongodb:
    image: mongo:4.2
    ports:
      - '27017:27017'
    volumes:
      - ./backend/dump:/dump/
    restart: unless-stopped

  mongo-yt-indexes:
    image: mongo:4.2
    container_name: mongo-yt-indexes
    volumes:
      - ./platforms/yttrex/backend/scripts:/scripts
    command: mongo mongodb:27017/yttrex /scripts/build-indexes.js
    depends_on:
      - mongodb

  mongo-tk-indexes:
    image: mongo:4.2
    container_name: mongo-tk-indexes
    volumes:
      - ./platforms/tktrex/backend/scripts:/scripts
    command: mongo mongodb:27017/tktrex /scripts/build-indexes.js
    depends_on:
      - mongodb

  mongo-yt-test-indexes:
    image: mongo:4.2
    container_name: mongo-yt-test-indexes
    volumes:
      - ./platforms/yttrex/backend/scripts:/scripts
    command: mongo mongodb:27017/yttrex-test /scripts/build-indexes.js
    depends_on:
      - mongodb

  mongo-tk-test-indexes:
    image: mongo:4.2
    container_name: mongo-tk-test-indexes
    volumes:
      - ./platforms/tktrex/backend/scripts:/scripts
    command: mongo mongodb:27017/tktrex-test /scripts/build-indexes.js
    depends_on:
      - mongodb

  build-from-zip:
    image: node:16-slim
    build:
      dockerfile: from-zip.Dockerfile
      context: .
      target: unzip
    entrypoint: /bin/sh
    container_name: build-from-zip
    stdin_open: true # docker run -i
    tty: true # docker run -t

  yt-backend:
    image: trex:yt-backend
    build:
      dockerfile: Dockerfile.ytbackend
      context: .

  yt-server:
    image: trex:yt-backend
    container_name: yt-server
    command: yarn start
    ports:
      - '9000:9000'
    env_file:
      - ./platforms/yttrex/backend/.env
    environment:
      - BACKEND_DEBUG=yttrex*,@trex*
      - mongoHost=mongodb
    depends_on:
      - yt-backend
      - mongodb
      - mongo-yt-indexes
    deploy:
      resources:
        limits:
          memory: 1000M

  yt-parser:
    image: trex:yt-backend
    container_name: yt-parser
    command: yarn parserv
    env_file:
      - ./platforms/yttrex/backend/.env
    environment:
      - PARSER_DEBUG=@trex:htmls:*,-@trex:htmls:debug
      - mongoHost=mongodb
    depends_on:
      - mongodb
      - mongo-yt-indexes
    deploy:
      resources:
        limits:
          memory: 2048M

  tk-backend:
    build:
      dockerfile: Dockerfile.tkbackend
      context: .
    container_name: tk-backend
    ports:
      - '14000:14000'
    environment:
      - DEBUG=*
      - mongoHost=mongodb
    depends_on:
      - mongodb
      - mongo-tk-indexes
