version: "3"


# to restore a dump from folder
# docker-compose exec -T mongo mongorestore /dump
services:
  base:
    build:
      context: .
      target: build
    scale: 0

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./backend/dump:/dump/

  mongo-indexes:
    image: mongo
    container_name: mongo-indexes
    links:
      - mongo
    volumes:
      - ./backend/scripts:/scripts
    command: mongo --host mongo /scripts/build-indexes.js
    depends_on:
      - mongo

  api:
    image: yttrex_base
    container_name: api
    ports:
      - "9002:9002"
    environment:
      DEBUG: "*,-body-parser*,-express*,-follow-redirects"
      key: my-dev-key
      mongoHost: mongo
    links:
      - mongo
    volumes:
      - ./shared:/app/shared
      - ./backend:/app/backend/
    depends_on:
      - mongo
    working_dir: /app/backend
    command: npm run watch

  ycai:
    image: yttrex_base
    ports:
      - "4005:4005"
    volumes:
      - ./tsconfig.json:/app/tsconfig.json
      - ./shared:/app/shared
      - ./YCAI:/app/YCAI
      - ./YCAI/build:/app/YCAI/build
    working_dir: /app/YCAI
    depends_on:
      - api
    command: npm run watch
