# Do not change this unless you really know what you're doing.
experimentType: tt-french-elections

# Set to a string such as socks5://localhost:9050
# to make puppeteer use a proxy.
#
# Leave it empty if you don't want to use a proxy.
#
# The option will be passed directly to chrome using
# the --proxy-server flag.
#
# Note: this is YAML, not JSON, so you do not need
# to wrap the string in quotes.
proxy:

# The URL to browse at the beginning of the script,
# before starting to type the queries.
baseURL: https://www.tiktok.com/fr

# Enable the stealth mode puppeteer plugin.
# This is useful to bypass some detections, but
# some things do not work well with this plugin so
# the option is offered to disable it.
useStealth: true
