name: TrEx - Release "daily"

on:
  push:
    branches:
      - daily

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    services:
      mongo-db:
        image: mongo:4.2
        ports:
          - 27017:27017
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn

      # - name: Shrink to zip
      #   run: |
      #     ./scripts/shrink.sh
      #     ./scripts/install-from-shrinkzip.sh ./build/trex.zip ./shrink-test

      - name: Build Dashboard
        env:
          DOTENV_CONFIG_PATH: .env.beta
          DEBUG: '@trex*,@YCAI*'
        run: yarn ycai build

      - name: Release Version
        run: yarn release-it --no-github.release --release-version

      - name: Deploy YCAI Dashboard
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./platforms/ycai/studio/build/dashboard/
          remote_path: ~/staging-studio/
          remote_host: ${{ secrets.YCAI_DAILY_DEPLOY_HOST }}
          remote_user: ${{ secrets.YCAI_DEPLOY_USER }}
          remote_key: ${{ secrets.YCAI_DEPLOY_KEY }}
