name: Guardoni - Pull Request

on:
  pull_request:
    branches:
      - daily
      - beta
    paths:
      - "packages/shared/**"
      - "extension/**"
      - "guardoni/**"

jobs:
  pull_request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install modules
        run: yarn

      - name: Lint code
        run: yarn guardoni lint

      - name: Build shared
        run: yarn shared build

      - name: Build extension for guardoni
        run: |
          yarn extension build
          yarn extension dist:guardoni

      - name: Build
        run: yarn guardoni build

      - name: Package
        run: yarn guardoni pkg
