name: Guardoni - Pull Request

on:
  pull_request:
    branches:
      - master
      - daily
      - beta
      - feat/**
      - fix/**
      - refactor/**
    paths:
      - "packages/shared/**"
      - "platforms/**/extension/**"
      - "platforms/guardoni/**"

jobs:
  pull_request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    services:
      mongo-db:
        image: mongo:4.2
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install modules
        run: yarn

      - name: Get version
        id: version
        run: |
          echo "::set-output name=version::$(npm pkg get version | sed 's/"//g')"

      - name: Lint code
        run: yarn guardoni lint

      - name: Build shared
        run: yarn shared build

      - name: Build guardoni
        run: |
          yarn guardoni build

      - name: Test
        run: |
          yarn pm2 start --env test platforms/yttrex/backend/ecosystem.config.js
          yarn pm2 start --env test platforms/tktrex/backend/ecosystem.config.js
          yarn yt:ext build:guardoni
          yarn tk:ext build:guardoni
          yarn test guardoni --ci

      - name: Package
        run: yarn guardoni pkg

      - name: Test package
        run: |
          ./platforms/guardoni/dist/guardoni-cli-${{ steps.version.outputs.version }}-linux --verbose --basePath "$(pwd)/platforms/guardoni" -c "$(pwd)/platforms/guardoni/guardoni.config.json" yt-list
          ./platforms/guardoni/dist/guardoni-cli-${{ steps.version.outputs.version }}-linux --verbose --basePath "$(pwd)/platforms/guardoni" -c "$(pwd)/platforms/guardoni/guardoni.config.json" tk-list
          yarn pm2 stop all
