name: TRex - Release Master

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          git config --global user.email "team@tracking.exposed"
          git config --global user.name "Team - Tracking Exposed"
          yarn release-it --ci

      - name: Build Dashboard
        env:
          DOTENV_CONFIG_PATH: .env
        run: yarn ycai build

      - name: Deploy YCAI Dashboard
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./platforms/ycai/studio/build/dashboard/
          remote_path: ~/studio-website/
          remote_host: ${{ secrets.YCAI_DEPLOY_HOST }}
          remote_user: ${{ secrets.YCAI_DEPLOY_USER }}
          remote_key: ${{ secrets.YCAI_DEPLOY_KEY }}

  build:
    name: Build
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - uses: actions/cache@v2
        with:
          key: build-workspace-${{ github.run_id }}
          path: |
            packages/shared/build
            packages/taboule/build
            extension/dist
            guardoni/build
            guardoni/dist
            YCAI/build
            platforms/tktrex/extension/build

      - name: Install dependencies
        run: yarn

      - name: YCAI dist
        env:
          NODE_ENV: production
        run: |
          yarn shared build
          yarn taboule build
          yarn yt:ext dist
          yarn yt:ext dist:guardoni
          yarn guardoni build
          yarn guardoni pkg
          yarn tk:ext build
          yarn ycai build

  guardoni_build:
    name: Guardoni build
    needs: build
    runs-on: ${{ matrix.config.os }}
    strategy:
      max-parallel: 1
      matrix:
        node-version: [16.x]
        config:
          - os: ubuntu-latest
            command: 'dist:linux'
          - os: macos-latest
            command: 'dist:mac'
          - os: windows-latest
            command: 'dist:windows'
    steps:
      - name: 'Use GNU tar instead BSD tar'
        if: matrix.config.os == 'windows-latest'
        shell: cmd
        run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          key: build-guardoni-${{ github.run_id }}-${{ matrix.config.os }}
          restore-keys: |
            build-guardoni-${{ github.run_id }}-macos-latest
            build-guardoni-${{ github.run_id }}-ubuntu-latest
            build-workspace-${{ github.run_id }}
          path: |
            packages/shared/build
            packages/taboule/build
            guardoni/build
            guardoni/dist
            platforms/tktrex/extension/build
            platforms/ycai/studio/build
            platforms/yttrex/extension/dist

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn

      - name: Build Guardoni for ${{ matrix.config.os }}
        env:
          DOTENV_CONFIG_PATH: .env.beta
        run: yarn guardoni ${{ matrix.config.command }}

  gh_release:
    name: Release on GH
    runs-on: ubuntu-latest
    needs: [release, build, guardoni_build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          key: build-${{ github.run_id }}
          restore-keys: |
            build-guardoni-${{ github.run_id }}-windows-latest
          path: |
            packages/shared/build
            packages/taboule/build
            extension/dist
            guardoni/build
            guardoni/dist
            platforms/tktrex/extension/build
            platforms/ycai/studio/build
            platforms/yttrex/extension/dist

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn

      - name: Get version
        id: version
        run: |
          echo "::set-output name=version::$(npm pkg get version | sed 's/"//g')"

      - name: Upload assets to release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          tag_name: v${{ steps.version.outputs.version }}
          files: |
            guardoni/dist/guardoni-cli*
            guardoni/dist/*.deb
            guardoni/dist/*.dmg
            guardoni/dist/Guardoni*.exe
            platforms/tktrex/extension/build/extension/*.zip
            platforms/ycai/studio/build/extension/*.zip
            platforms/yttrex/extension/dist/yttrex-*.zip
            platforms/yttrex/extension/dist/guardoni-yttrex-*.zip
