name: TkTrEx - Pull Request

on:
  pull_request:
    branches:
      - daily
      - beta
      - feat/**
      - fix/**
      - refactor/**
    paths:
      - "packages/**"
      - "platforms/tktrex/**"

jobs:
  pull_request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['4.2']

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install modules
        run: yarn

      - name: Lint code
        run: |
          yarn tk:backend lint
          yarn tk:ext lint

      - name: Build shared
        run: yarn shared build

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-port: 27019
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Test platform
        run: |
          yarn pm2 start --env test platforms/tktrex/backend/ecosystem.config.js
          # yarn tk:backend test --runInBand --ci
          yarn test tktrex/extension --runInBand --ci
          yarn pm2 stop all

      - name: Build
        run: |
          yarn tk:ext build
