name: TkTrEx - Pull Request

on:
  push:
    branches:
      - daily
  pull_request:
    branches:
      - daily
      - beta
      - feat/**
      - fix/**
      - refactor/**
    paths:
      - "packages/**"
      - "platforms/tktrex/**"

env:
  TK_IMAGE_NAME: tk-backend

jobs:
  pull_request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['4.2']
    services:
      mongo-db:
        image: mongo:4.2
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install modules
        run: yarn

      - name: Lint code
        run: |
          yarn tk:backend lint
          yarn tk:ext lint

      - name: Build shared
        run: yarn shared build

      - name: Build Backend
        run: yarn tk:backend build

      - name: Build
        run: yarn tk:ext build

      - name: Spec tests
        run: yarn tk:ext test --runInBand --ci

      - name: Test platform
        run: |
          yarn pm2 start platforms/tktrex/backend/ecosystem.config.js --env test
          yarn tk:backend test --runInBand --ci --forceExit
          yarn pm2 stop all

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build TK Backend image
        run: docker build . --file Dockerfile.tkbackend --tag $TK_IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"


