name: TkTrEx - Pull Request

on:
  push:
    branches:
      - daily
  pull_request:
    branches:
      - daily
      - beta
      - feat/**
      - fix/**
      - refactor/**
    paths:
      - 'packages/**'
      - 'platforms/tktrex/**'

jobs:
  pull_request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['4.2']
    services:
      mongo-db:
        image: mongo:4.2
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install modules
        run: yarn

      - name: Lint code
        run: |
          yarn tk:backend lint
          yarn tk:ext lint

      - name: Build shared
        run: yarn shared build

      - name: Build Backend
        run: yarn tk:backend build

      - name: Build
        run: yarn tk:ext build

      - name: Spec tests
        run: yarn tk:ext test --runInBand --ci

      - name: Start pm2
        run: |
          yarn pm2 start platforms/tktrex/backend/ecosystem.config.js --env test
          sleep 5

      - name: Test platform
        run: yarn tk:backend test --runInBand --ci --forceExit

      - name: Stop pm2
        run: yarn pm2 stop all
