name: YCAI - Pull Request

on:
  pull_request:
    branches:
      - daily
      - beta

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
          persist-credentials: false

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::~/.npm"

      - uses: actions/cache@v2
        id: npm-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('YCAI/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('YCAI/package-lock.json') }}

      - name: Install modules
        working-directory: ./YCAI
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
          persist-credentials: false

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('YCAI/package-lock.json') }}

      - name: Lint code
        working-directory: ./YCAI
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
          persist-credentials: false

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('YCAI/package-lock.json') }}

      - name: Build
        working-directory: ./YCAI
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
          persist-credentials: false

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('YCAI/package-lock.json') }}

      - name: Test
        working-directory: ./YCAI
        run: npm test
