name: YCAI - Pull Request

on:
  pull_request:
    branches:
      - daily
      - beta
    paths:
      - "shared/**"
      - "YCAI/**"

defaults:
  run:
    working-directory: YCAI

jobs:
  pull_request:
    runs-on: ubuntu-latest
    matrix:
      mongo-version: [4.2]
    steps:
      - uses: actions/checkout@v2

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::~/.npm"

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install shared modules
        working-directory: shared
        run: npm i

      - name: Install YCAI modules
        run: npm i

      - name: Lint code
        run: npm run lint

      - name: Build extension for tests
        run: npm run build:dev

      - name: Test spec
        run: npm test spec

      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Start api service
        working-directory: yttrex-backend/backend
        run: docker-compose up -d api

      - name: Log what's going on in docker
        working-directory: yttrex-backend/backend 
        run: docker-compose logs api

      - name: Test Code
        uses: mujo-code/puppeteer-headful@v2
        env:
          CI: true
        with:
          args: npm test e2e -- --watchAll=false

      - name: Stop api service
        working-directory: yttrex-backend/backend
        run: docker-compose down
