name: YCAI - Pull Request

on:
  pull_request:
    branches:
      - daily
      - beta
    paths:
      - "shared/**"
      - "YCAI/**"

defaults:
  run:
    working-directory: YCAI

jobs:
  pull_request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::~/.npm"

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install modules
        working-directory: shared
        run: npm i

      - name: Install modules
        run: npm i

      - name: Lint code
        run: npm run lint

      - name: Build shared
        working-directory: ./shared
        run: npm run build

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
