name: YTTrEx - Pull Request

on:
  pull_request:
    branches:
      - daily
      - beta
      - feat/**
      - fix/**
      - refactor/**
    paths:
      - "shared/**"
      - "platforms/yttrex/**"

jobs:
  pull_request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['4.2']

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install modules
        working-directory: ./
        run: yarn

      - name: Lint code
        run: yarn yt:ext lint

      - name: Build
        run: |
          yarn shared build
          yarn yt:ext build

      - name: Pack
        run: yarn yt:ext pack

      - name: Lint code
        run: yarn yt:backend lint

      - name: Build backend
        run: yarn yt:backend build

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-port: 27019
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Test
        run: yarn yt:backend test --runInBand --forceExit --ci

