name: YTTrEx - Pull Request

on:
  push:
    branches:
      - daily
  pull_request:
    branches:
      - daily
      - beta
      - feat/**
      - fix/**
      - refactor/**
    paths:
      - "shared/**"
      - "platforms/yttrex/**"

jobs:
  pull_request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['4.2']
    services:
      mongo-db:
        image: mongo:4.2
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install modules
        working-directory: ./
        run: yarn

      - name: Lint code
        run: yarn yt:ext lint

      - name: Type Check
        run: yarn yt:ext tsc -b

      - name: Build
        run: |
          yarn yt:ext clean
          yarn yt:ext build

      - name: Pack
        run: yarn yt:ext pack

      - name: Lint code
        run: yarn yt:backend lint

      - name: Build backend
        run: yarn yt:backend build

      - name: Test Extension
        run: yarn yt:ext test --runInBand --ci

      - name: Test backend
        run: |
          yarn pm2 start platforms/yttrex/backend/ecosystem.config.js  --env test
          yarn yt:backend test --runInBand --forceExit --ci
          yarn pm2 stop all

